@startuml Foco 
 
 class Usuario

 class Foco {
    -EstadoFoco estado
    +Encender()
    +Apagar()
    +LeerEstado
 }



 class EstadoFoco 
 class SerieFocos{
   -Foco focos [10]
   +MostrarFocos()
 }

 Usuario o-- Foco
 Foco *-- EstadoFoco
EstadoFoco --|> Booleano
SerieFocos "1" *-- "10" Foco
Usuario o-- SerieFocoS
I
 @enduml